version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mycameraapp-postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mycameraapp

  redis:
    image: redis:latest
    container_name: mycameraapp-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  mycameraapp:
    build:
      context: .
    image: mycameraapp:latest
    container_name: mycameraapp
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ENV=development
      - MYCAMERAAPP_DB_DSN=postgresql://postgres:mysecretpassword@postgres:5432/mycameraapp


    depends_on:
      - postgres
      - redis
