ALTER TABLE cameras DROP CONSTRAINT IF EXISTS resolution_check;
ALTER TABLE cameras DROP CONSTRAINT IF EXISTS weight_check;
ALTER TABLE cameras DROP CONSTRAINT IF EXISTS zoom_check;
ALTER TABLE cameras DROP CONSTRAINT IF EXISTS model_check;

